CI: Install multiple JDK versions, update to Maven 3.9.5
Seems multiple JDK versions are needed within the ccsdk/ project hierarchy.

The last CBOM workflow run in ccsdk-sli/ failed with the error below:

Error:  Failed to execute goal org.opendaylight.odlparent:copy-files-plugin:14.0.8:copy-files (default) on project utils-provider: The plugin org.opendaylight.odlparent:copy-files-plugin:14.0.8 requires Maven version 3.9.5

This would suggest a more recent Maven release is required.

Change-Id: I5324ae6262f1241a5fe3c119ea5aec5a48ae77f7
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>